services:
  urna_backend:
    build:
      context: .
      dockerfile: ./.docker/backend/Dockerfile
    container_name: urna-backend
    env_file:
      - .env
    ports:
      - "7000:7000"
    depends_on:
      - redis

  urna_redis:
    image: "redis:latest"
    container_name: redis
    env_file:
      - .env
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
